// Builds the playable page from src/. Run: node scripts/build.mjs
//   index.html        the game as a standalone page (three.js from vendor/), served by GitHub Pages
//   dist/artifact.html the same page as a fragment with three.js from a CDN, for publishing as a Claude artifact
//   sw.js              the service worker, stamped with this build's version
import fs from 'node:fs';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
// where GitHub Pages serves the game: link previews need absolute addresses
const SITE = 'https://aykhan-dev.github.io/sum-sort/';
const BLURB = 'Fill every candy jar with tiles that add up to its number. 100 levels, endless more, and a new daily puzzle every day.';
const root = fileURLToPath(new URL('..', import.meta.url));
const read = f => fs.readFileSync(root + f, 'utf8');
const src = read('src/page.src.html');
// pure modules, in dependency order: their imports of each other are dropped, their exports become plain declarations
const MODULES = ['src/logic.mjs', 'src/meta.mjs'];
const logic = MODULES.filter(f => fs.existsSync(root + f))
  .map(f => read(f).replace(/^import [^\n]* from '\.\/[\w.-]+';\n/gm, '').replace(/^export /gm, '')).join('\n');
const levels = read('src/levels.json').trim();
// the daily pool, one board per line in the source, packed tight in the page
const dailies = JSON.stringify(JSON.parse(read('src/dailies.json')));
for (const ph of ['/*__LOGIC__*/', '/*__LEVELS__*/', '/*__DAILIES__*/']) if (!src.includes(ph)) throw new Error(ph + ' placeholder missing in src/page.src.html');
const page = src.replace('/*__LOGIC__*/', () => logic).replace('/*__LEVELS__*/', () => levels).replace('/*__DAILIES__*/', () => dailies);

const CDN = 'https://cdn.jsdelivr.net/npm/three@0.170.0/';
if (!page.includes(CDN + 'build/three.module.js')) throw new Error('three.js import map not found');
const local = page.replace(CDN + 'build/three.module.js', './vendor/three/three.module.min.js').replace(CDN + 'examples/jsm/', './vendor/three/addons/');
const head = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#F7DAD0">
<meta name="description" content="${BLURB}">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<meta name="apple-mobile-web-app-title" content="Sum Sort">
<meta name="mobile-web-app-capable" content="yes">
<meta property="og:type" content="website">
<meta property="og:url" content="${SITE}">
<meta property="og:title" content="Sum Sort">
<meta property="og:description" content="${BLURB}">
<meta property="og:image" content="${SITE}og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Sum Sort: glass candy jars and numbered gummy tiles on a pink counter">
<meta name="twitter:card" content="summary_large_image">
<style>html,body{margin:0;padding:0}[hidden]:not([hidden=until-found i]){display:none!important}</style>
</head>
<body>
`;
// the source starts with <title> and font links: those belong in the head of a standalone page
const cut = local.indexOf('<style>');
fs.writeFileSync(root + 'index.html', head.replace('</head>', local.slice(0, cut).replace('Sum Sort Prototype', 'Sum Sort') + '</head>') + local.slice(cut) + '\n</body>\n</html>\n');
// the service worker's cache is named after this build, so a new build replaces the old cache
const version = crypto.createHash('sha256').update(fs.readFileSync(root + 'index.html')).digest('hex').slice(0, 12);
fs.writeFileSync(root + 'sw.js', '// generated by scripts/build.mjs from src/sw.src.js, do not edit\n' + read('src/sw.src.js').replace('__VERSION__', version));
fs.mkdirSync(root + 'dist', { recursive: true });
fs.writeFileSync(root + 'dist/artifact.html', page);
console.log('built index.html', (head.length + local.length), 'bytes');
